config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'tweets#index'
  resources :users
  resources :tweets

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '風景' },
    { id: 3, name: '野生動物' },
    { id: 4, name: 'マクロ' },
    { id: 5, name: '水中' },
    { id: 6, name: '天体' },
    { id: 7, name: '航空' },
    { id: 8, name: 'ポートレート' },
    { id: 9, name: 'ブライダル' },
    { id: 10, name: 'スポーツ' },
    { id: 11, name: 'ファッション' },
    { id: 12, name: 'ストリートスナップ' },
    { id: 13, name: 'イベント' },
    { id: 14, name: '旅行' },
    { id: 15, name: '都市風景' },
    { id: 16, name: '商品' },
    { id: 17, name: '料理' },
    { id: 18, name: '建築' },
    { id: 19, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :tweets

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, { id: 7, name: '山形県' },
    { id: 8, name: '福島県' }, { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' }, { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' }, { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' }, { id: 18, name: '石川県' }, { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' }, { id: 21, name: '長野県' }, { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :tweets
  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :prefecture

  validates :image, presence: {message:'選択してください'}
  validates :title, :explain, :city, presence: true
  validates :category_id, :prefecture_id, numericality: {other_than: 1, message:'を選択してください' }

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :nickname, presence: true 
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates_format_of :password, { with: PASSWORD_REGEX, message: '半角英数字で入力して下さい' }
    validates :password, presence: true, length: { minimum: 8 }

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :introduction])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end



  private 

  def tweet_params
    params.require(:tweet).permit(:image, :title, :explain, :category_id, :prefecture_id, :city, :house_number).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asobitweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">AsobiTweet</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <%= link_to "投稿する", new_tweet_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/tweets/index.html.erb
<%# <div class="tweet">
  <div class="upper-tweet">
    <div class="tweet-user">
      <%= tweet.user.name %>
    <%# </div>
  </div>
  <div class= "lower-tweet">
    <div class="tweet.title">
      <%= tweet.titile %>
    <%# </div>
      <%= image_tag tweet.image, class: 'tweet-image' if tweet.image.attached? %>
  <%# </div>
</div> %> 

<div class="contents row">
  
</div>

app/views/tweets/new.html.erb
<div class="contents row">
 
  <div class="container">
    <h3>投稿する</h3>
    <div class="content">
      <%= form_with(model: @tweet, local: true) do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
    <div class="img-upload">
      <div class="img-text">
      投稿画像
      <span class="indispensable">必須</span>
      </div>
      <div class="click-uplaod">
        <p>クリックしてファイルをアップロード</p>
        <%= f.file_field :image, id:"tweet-image" %>
      </div>
    </div>

    <div class="tweet-title">
      <div class="title-text">
      タイトル
      <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :title, placeholder: "タイトル" %>
    </div>

    <div class="tweet-explain">
      <div class="explain-text">
      ポイント
      <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :explain, placeholder: "text", rows: "10" %>
    </div>

    <div class="tweet-category">
      <div class="category-number">
      カテゴリー
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"tweet-category"}) %>
    </div>

    <div class="tweet-prefecture">
      <div class="prefecture-number">
      都道府県
      </div>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    </div>

     <div class="tweet-city">
      <div class="city-text">
      市町村
      <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :city, placeholder: "市町村" %>
    </div>

    <div class="tweet-house_number">
      <div class="house_number-text">
      番地
      <span class="any">任意</span>
      </div>
      <%= f.text_field :house_number, placeholder: "番地" %>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to '戻る', root_path, class:"back-btn" %>
    </div>
    <% end %>
    </div>
  </div>
</div>